#!/usr/bin/env python3
"""Generate src/stubs.c from include/webgpu/webgpu.h.

Every WGPU_EXPORT function that is not implemented by hand in
src/remote_webgpu.c or src/remote_methods.c gets a stub that aborts with a
clear message, so an unimplemented entry point is immediately obvious at
runtime.  The implemented set is derived by scanning those sources for
function definitions (a `wgpu...(` at the start of a line).

wgpuGetProcAddress is also generated here: a table of every declared
function (implemented or stub -- both are valid addresses).

Run from the remote_webgpu directory:

    python3 tools/generate_stubs.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "include" / "webgpu" / "webgpu.h"
SOURCES = [ROOT / "src" / "remote_webgpu.c", ROOT / "src" / "remote_methods.c"]
OUTPUT = ROOT / "src" / "stubs.c"

DECL = re.compile(
    r"^WGPU_EXPORT\s+(?P<ret>.+?)\s+(?P<name>wgpu\w+)\((?P<args>.*)\)\s+"
    r"WGPU_FUNCTION_ATTRIBUTE;\s*$"
)
# A definition: return type and function name at the start of a line.
DEFINITION = re.compile(r"^[A-Za-z_][\w \*]*?\b(wgpu\w+)\(", re.M)


def param_names(args: str):
    if args.strip() in ("", "void"):
        return []
    names = []
    for arg in args.split(","):
        idents = re.findall(r"[A-Za-z_]\w*", arg)
        names.append(idents[-1])
    return names


def main():
    implemented = set()
    for source in SOURCES:
        implemented.update(DEFINITION.findall(source.read_text()))

    seen = set()
    decls = []
    for line in HEADER.read_text().splitlines():
        m = DECL.match(line)
        if not m:
            continue
        name = m.group("name")
        if name in seen:
            continue  # the header declares every function twice
        seen.add(name)
        if name in implemented or name == "wgpuGetProcAddress":
            continue
        decls.append(m)

    out = [
        "/* Generated by tools/generate_stubs.py -- do not edit by hand. */",
        "",
        '#include "remote_webgpu_internal.h"',
        "",
        "#include <string.h>",
        "",
        "#include <webgpu/webgpu.h>",
        "",
    ]
    for m in decls:
        ret, name, args = m.group("ret"), m.group("name"), m.group("args")
        out.append(f"{ret} {name}({args})")
        out.append("{")
        for p in param_names(args):
            out.append(f"    (void){p};")
        out.append(f'    remote_wgpu_unimplemented("{name}");')
        out.append("}")
        out.append("")

    out += [
        "/* Every declared function, implemented or stub. */",
        "typedef struct RwProcEntry {",
        "    const char *name;",
        "    WGPUProc proc;",
        "} RwProcEntry;",
        "",
        "static const RwProcEntry rw_procs[] = {",
    ]
    for name in sorted(seen - {"wgpuGetProcAddress"}):
        out.append(f'    {{ "{name}", (WGPUProc){name} }},')
    out += [
        "};",
        "",
        "WGPUProc wgpuGetProcAddress(WGPUStringView procName)",
        "{",
        "    if (!procName.data)",
        "        return NULL;",
        "    for (size_t i = 0; i < sizeof rw_procs / sizeof rw_procs[0]; ++i) {",
        "        const char *name = rw_procs[i].name;",
        "        if (strlen(name) == procName.length",
        "            && memcmp(name, procName.data, procName.length) == 0)",
        "            return rw_procs[i].proc;",
        "    }",
        "    return NULL;",
        "}",
        "",
    ]

    OUTPUT.write_text("\n".join(out))
    print(f"wrote {OUTPUT} ({len(decls)} stubs, {len(implemented)} implemented by hand)")


if __name__ == "__main__":
    main()
