#!/usr/bin/env python3
"""Generate src/stubs.c from include/webgpu/webgpu.h.

Every WGPU_EXPORT function that is not implemented by hand in
src/remote_webgpu.c gets a stub that aborts with a clear message, so an
unimplemented entry point is immediately obvious at runtime.

Run from the remote_webgpu directory:

    python3 tools/generate_stubs.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "include" / "webgpu" / "webgpu.h"
OUTPUT = ROOT / "src" / "stubs.c"

# Implemented by hand in remote_webgpu.c; keep this list in sync.
IMPLEMENTED = {
    "wgpuCreateInstance",
    "wgpuInstanceAddRef",
    "wgpuInstanceRelease",
    "wgpuInstanceProcessEvents",
    "wgpuInstanceCreateSurface",
    "wgpuAdapterAddRef",
    "wgpuAdapterRelease",
    "wgpuAdapterRequestDevice",
    "wgpuAdapterGetInfo",
    "wgpuAdapterInfoFreeMembers",
    "wgpuDeviceAddRef",
    "wgpuDeviceRelease",
    "wgpuDeviceGetQueue",
    "wgpuQueueAddRef",
    "wgpuQueueRelease",
    "wgpuSurfaceAddRef",
    "wgpuSurfaceRelease",
    "wgpuSurfaceGetCapabilities",
    "wgpuSurfaceCapabilitiesFreeMembers",
    "wgpuSurfaceConfigure",
    # remote_methods.c
    "wgpuDeviceCreateShaderModule",
    "wgpuShaderModuleAddRef",
    "wgpuShaderModuleRelease",
    "wgpuDeviceCreateBuffer",
    "wgpuBufferDestroy",
    "wgpuBufferMapAsync",
    "wgpuBufferGetConstMappedRange",
    "wgpuBufferUnmap",
    "wgpuBufferAddRef",
    "wgpuBufferRelease",
    "wgpuDeviceCreateBindGroupLayout",
    "wgpuBindGroupLayoutAddRef",
    "wgpuBindGroupLayoutRelease",
    "wgpuDeviceCreateBindGroup",
    "wgpuBindGroupAddRef",
    "wgpuBindGroupRelease",
    "wgpuDeviceCreatePipelineLayout",
    "wgpuPipelineLayoutAddRef",
    "wgpuPipelineLayoutRelease",
    "wgpuDeviceCreateRenderPipeline",
    "wgpuRenderPipelineAddRef",
    "wgpuRenderPipelineRelease",
    "wgpuSurfaceGetCurrentTexture",
    "wgpuSurfacePresent",
    "wgpuTextureCreateView",
    "wgpuTextureGetWidth",
    "wgpuTextureGetHeight",
    "wgpuTextureAddRef",
    "wgpuTextureRelease",
    "wgpuTextureViewAddRef",
    "wgpuTextureViewRelease",
    "wgpuDeviceCreateCommandEncoder",
    "wgpuCommandEncoderBeginRenderPass",
    "wgpuCommandEncoderCopyTextureToBuffer",
    "wgpuCommandEncoderFinish",
    "wgpuCommandEncoderAddRef",
    "wgpuCommandEncoderRelease",
    "wgpuRenderPassEncoderSetPipeline",
    "wgpuRenderPassEncoderSetBindGroup",
    "wgpuRenderPassEncoderSetVertexBuffer",
    "wgpuRenderPassEncoderDraw",
    "wgpuRenderPassEncoderEnd",
    "wgpuRenderPassEncoderAddRef",
    "wgpuRenderPassEncoderRelease",
    "wgpuCommandBufferAddRef",
    "wgpuCommandBufferRelease",
    "wgpuQueueWriteBuffer",
    "wgpuQueueSubmit",
}

DECL = re.compile(
    r"^WGPU_EXPORT\s+(?P<ret>.+?)\s+(?P<name>wgpu\w+)\((?P<args>.*)\)\s+"
    r"WGPU_FUNCTION_ATTRIBUTE;\s*$"
)


def param_names(args: str):
    if args.strip() in ("", "void"):
        return []
    names = []
    for arg in args.split(","):
        idents = re.findall(r"[A-Za-z_]\w*", arg)
        names.append(idents[-1])
    return names


def main():
    seen = set()
    decls = []
    for line in HEADER.read_text().splitlines():
        m = DECL.match(line)
        if not m:
            continue
        name = m.group("name")
        if name in seen:
            continue  # the header declares every function twice
        seen.add(name)
        if name in IMPLEMENTED:
            continue
        decls.append(m)

    out = [
        "/* Generated by tools/generate_stubs.py -- do not edit by hand. */",
        "",
        '#include "remote_webgpu_internal.h"',
        "",
        "#include <webgpu/webgpu.h>",
        "",
    ]
    for m in decls:
        ret, name, args = m.group("ret"), m.group("name"), m.group("args")
        out.append(f"{ret} {name}({args})")
        out.append("{")
        for p in param_names(args):
            out.append(f"    (void){p};")
        out.append(f'    remote_wgpu_unimplemented("{name}");')
        out.append("}")
        out.append("")

    OUTPUT.write_text("\n".join(out))
    print(f"wrote {OUTPUT} ({len(decls)} stubs, {len(IMPLEMENTED)} implemented by hand)")


if __name__ == "__main__":
    main()
