#!/usr/bin/env python3
"""Generate src/ffi.rs from ../../remote_webgpu/include/webgpu/webgpu.h.

The header is machine-generated and regular, so a line-oriented parser is
enough: opaque handles, enums (emitted as integer type aliases + consts, to
avoid UB from out-of-range values), flag typedefs with their `static const`
values, structs, callback typedefs and WGPU_EXPORT function declarations.

Run from the remote-wgpu-sys directory:

    python3 tools/generate_ffi.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / ".." / ".." / "remote_webgpu" / "include" / "webgpu" / "webgpu.h"
OUTPUT = ROOT / "src" / "ffi.rs"

BASE_TYPES = {
    "uint64_t": "u64",
    "uint32_t": "u32",
    "uint16_t": "u16",
    "uint8_t": "u8",
    "int64_t": "i64",
    "int32_t": "i32",
    "int16_t": "i16",
    "int8_t": "i8",
    "size_t": "usize",
    "float": "f32",
    "double": "f64",
    "char": "c_char",
    "void": "c_void",
    "WGPUBool": "WGPUBool",
    "WGPUFlags": "WGPUFlags",
}

KEYWORDS = {"type", "ref", "loop", "move", "box"}

known_enums = set()
known_flags = set()
known_callbacks = set()
known_structs = set()
known_handles = set()


def rust_ident(name: str) -> str:
    return f"r#{name}" if name in KEYWORDS else name


def map_type(ctype: str) -> str:
    """Map a C type expression (without the field name) to Rust."""
    ctype = ctype.replace("WGPU_NULLABLE", "").strip()
    is_const = bool(re.search(r"\bconst\b", ctype))
    ctype = re.sub(r"\bconst\b", "", ctype)
    ctype = re.sub(r"\bstruct\b", "", ctype)
    stars = ctype.count("*")
    base = ctype.replace("*", "").strip()
    rust = BASE_TYPES.get(base, base)
    for _ in range(stars):
        rust = ("*const " if is_const else "*mut ") + rust
    return rust


def split_args(args: str):
    args = args.strip()
    if args in ("", "void"):
        return []
    out = []
    for arg in args.split(","):
        arg = arg.strip()
        m = re.match(r"^(?P<type>.+?)(?P<name>[A-Za-z_]\w*)$", arg)
        assert m, arg
        out.append((rust_ident(m.group("name")), map_type(m.group("type"))))
    return out


def fn_sig(ret: str, args: str) -> str:
    params = ", ".join(f"{n}: {t}" for n, t in split_args(args))
    rust_ret = map_type(ret)
    suffix = "" if rust_ret == "c_void" else f" -> {rust_ret}"
    return f"({params}){suffix}"


def main() -> None:
    text = HEADER.read_text()
    # Strip block comments so struct/enum bodies are plain field lines.
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)

    out = [
        "// Generated by tools/generate_ffi.py -- do not edit by hand.",
        "#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]",
        "use std::os::raw::{c_char, c_void};",
        "",
        "pub type WGPUFlags = u64;",
        "pub type WGPUBool = u32;",
        "",
        "pub const WGPU_WHOLE_SIZE: u64 = u64::MAX;",
        "pub const WGPU_WHOLE_MAP_SIZE: usize = usize::MAX;",
        "pub const WGPU_LIMIT_U32_UNDEFINED: u32 = u32::MAX;",
        "pub const WGPU_LIMIT_U64_UNDEFINED: u64 = u64::MAX;",
        "pub const WGPU_DEPTH_SLICE_UNDEFINED: u32 = u32::MAX;",
        "pub const WGPU_ARRAY_LAYER_COUNT_UNDEFINED: u32 = u32::MAX;",
        "pub const WGPU_MIP_LEVEL_COUNT_UNDEFINED: u32 = u32::MAX;",
        "pub const WGPU_COPY_STRIDE_UNDEFINED: u32 = u32::MAX;",
        "pub const WGPU_QUERY_SET_INDEX_UNDEFINED: u32 = u32::MAX;",
        "pub const WGPU_STRLEN: usize = usize::MAX;",
        "",
    ]

    # Opaque handles.
    for m in re.finditer(r"typedef struct (WGPU\w+)Impl\s*\*\s*(WGPU\w+)", text):
        impl, name = m.groups()
        known_handles.add(name)
        out.append(f"#[repr(C)] pub struct {impl}Impl {{ _unused: [u8; 0] }}")
        out.append(f"pub type {name} = *mut {impl}Impl;")
    out.append("")

    # Enums.
    for m in re.finditer(r"typedef enum (WGPU\w+) \{(.*?)\} \1", text, re.S):
        name, body = m.groups()
        known_enums.add(name)
        out.append(f"pub type {name} = u32;")
        for vm in re.finditer(r"(WGPU\w+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", body):
            out.append(f"pub const {vm.group(1)}: {name} = {vm.group(2)};")
        out.append("")

    # Flag typedefs and their values.
    for m in re.finditer(r"typedef WGPUFlags (WGPU\w+);", text):
        name = m.group(1)
        known_flags.add(name)
        out.append(f"pub type {name} = WGPUFlags;")
    out.append("")
    for m in re.finditer(
        r"static const (WGPU\w+) (WGPU\w+) = (0x[0-9A-Fa-f]+|\d+)", text
    ):
        ty, name, value = m.groups()
        out.append(f"pub const {name}: {ty} = {value};")
    out.append("")

    # Callback typedefs (including WGPUProc).
    for m in re.finditer(
        r"typedef ([\w ]+?)\s*\(\s*\*\s*(WGPU\w+)\s*\)\s*\((.*?)\)", text, re.S
    ):
        ret, name, args = m.groups()
        known_callbacks.add(name)
        args = " ".join(args.split())
        out.append(
            f'pub type {name} = Option<unsafe extern "C" fn{fn_sig(ret, args)}>;'
        )
    out.append("")

    # Structs.
    for m in re.finditer(r"typedef struct (WGPU\w+) \{(.*?)\} \1", text, re.S):
        name, body = m.groups()
        known_structs.add(name)
        out.append("#[repr(C)]")
        out.append("#[derive(Copy, Clone)]")
        out.append(f"pub struct {name} {{")
        for line in body.split(";"):
            line = " ".join(line.split())
            if not line:
                continue
            fm = re.match(r"^(?P<type>.+?)(?P<name>[A-Za-z_]\w*)$", line)
            assert fm, f"{name}: {line!r}"
            out.append(
                f"    pub {rust_ident(fm.group('name'))}: {map_type(fm.group('type'))},"
            )
        out.append("}")
        out.append("")

    # Functions.
    out.append('unsafe extern "C" {')
    seen = set()
    for line in HEADER.read_text().splitlines():
        fm = re.match(
            r"^WGPU_EXPORT\s+(?P<ret>.+?)\s+(?P<name>wgpu\w+)\((?P<args>.*)\)\s+"
            r"WGPU_FUNCTION_ATTRIBUTE;\s*$",
            line,
        )
        if not fm or fm.group("name") in seen:
            continue
        seen.add(fm.group("name"))
        out.append(
            f'    pub fn {fm.group("name")}{fn_sig(fm.group("ret"), fm.group("args"))};'
        )
    out.append("}")
    out.append("")

    # Layout self-check: a generated C file exports each struct's sizeof, and
    # a generated Rust test compares them against the Rust definitions.
    names = sorted(known_structs)
    csrc = [
        "/* Generated by tools/generate_ffi.py -- do not edit by hand. */",
        "#include <stdint.h>",
        "#include <webgpu/webgpu.h>",
        "",
        "const uint64_t rwgpu_struct_sizes[] = {",
    ]
    csrc += [f"    sizeof({n})," for n in names]
    csrc += ["};", ""]
    (ROOT / "src" / "struct_sizes.c").write_text("\n".join(csrc))
    rsrc = [
        "// Generated by tools/generate_ffi.py -- do not edit by hand.",
        "use super::ffi::*;",
        "unsafe extern \"C\" {",
        f"    static rwgpu_struct_sizes: [u64; {len(names)}];",
        "}",
        "#[test]",
        "fn struct_sizes_match_c() {",
        "    let rust_sizes: [(&str, u64); %d] = [" % len(names),
    ]
    rsrc += [f'        ("{n}", size_of::<{n}>() as u64),' for n in names]
    rsrc += [
        "    ];",
        "    for (i, (name, size)) in rust_sizes.iter().enumerate() {",
        "        assert_eq!(*size, unsafe { rwgpu_struct_sizes[i] }, \"size mismatch for {name}\");",
        "    }",
        "}",
        "",
    ]
    (ROOT / "src" / "size_check.rs").write_text("\n".join(rsrc))

    OUTPUT.write_text("\n".join(out))
    print(
        f"wrote {OUTPUT}: {len(known_handles)} handles, {len(known_enums)} enums, "
        f"{len(known_structs)} structs, {len(known_callbacks)} callbacks, {len(seen)} fns"
    )


if __name__ == "__main__":
    main()
